name: Parse and upload provenance data

on:
  workflow_call:
    inputs:
      filename:
        description: "mei file you want to change"
        required: True
        type: string
      commit_message:
        description: "The commit message"
        required: False
        default: "Ensured all corrs have a cert"
        type: string

jobs:
  run-shared-script:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout caller repository
      - name: Checkout caller repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: caller-repo

      # 2. Checkout shared repository (this repo)
      - name: Checkout shared repository
        uses: actions/checkout@v4
        with:
          repository: e-laute/automation
          ref: main
          path: shared-actions

      # 3. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: "shared-actions/scripts/requirements-dispatch.txt"

      # 4. Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r shared-actions/scripts/requirements-dispatch.txt

      # 5. Run the shared script *on the caller repo*
      - name: Run shared Python script
        run: |
          python shared-actions/scripts/ensure_corrs_have_cert.py ${{ inputs.filename }}

      # 6. Commit changes
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: ${{ inputs.commit_message }}
          repository: caller-repo
